#!/bin/sh

#------------------------------------------------------------------------------#
# "main"

fdroid=~/code/fdroid/fdroidserver/fdroid

if [ $# -gt 0 ]; then
    apksource=$1
else
    apksource=~jenkins/
fi

if [ ! -d $apksource ]; then
    echo "APK source dir '$apksource' does not exist! Specify one:"
    echo "$0 /path/to/folder/with/apks"
    exit 1
fi

test -d repo || mkdir repo

for f in `find $apksource -name '*.apk' | grep -F -v -e unaligned -e unsigned`; do
    name=$(basename $(dirname `dirname $f`))
    echo "name $name"
    apk=`aapt d badging "$f" | sed -n "s,^package: name='\(.*\)' versionCode='\([0-9][0-9]*\)' .*,\1_\2.apk,p"`
    # first try a hard link, then fall back to rsync to copy
    echo "$f --> repo/$apk"
    ln $f repo/$apk || \
        rsync -axv $f repo/$apk
done

test -e config.py || $fdroid init --keystore ./keystore.jks
$fdroid update -c
