#!/bin/sh

#------------------------------------------------------------------------------#
# "main"

if [ $# -gt 0 ]; then
    apksource=$1
else
    apksource=~jenkins/
fi

if [ $# -gt 1 ]; then
    fdroid=$2
else
    fdroid="fdroid"
fi

if [ ! -d $apksource ]; then
    echo "APK source dir '$apksource' does not exist! Specify one:"
    echo "$0 /path/to/folder/with/apks [/path/to/fdroidserver/fdroid]"
    exit 1
fi

test -d repo || mkdir repo
test -e config.py || $fdroid init --keystore ./keystore.jks --verbose

update=`dirname $0`/update-debug-fdroid-repo
$update $apksource $fdroid
