#!/bin/sh

set -e
set -x

if [ $# -gt 0 ]; then
    apksource=$1
else
    apksource=~jenkins/
fi

if [ $# -gt 1 ]; then
    fdroid=$2
else
    fdroid="fdroid"
fi

if [ ! -d $apksource ]; then
    echo "APK source dir '$apksource' does not exist! Specify one:"
    echo "$0 /path/to/folder/with/apks [/path/to/fdroidserver/fdroid]"
    exit 1
fi

# allow the location of aapt to be overridden
if [ -z "$aapt" ]; then
    aapt=`ls -1 $ANDROID_HOME/build-tools/*/aapt | sort | tail -1`
fi

test -x $aapt || exit
test -d repo || exit
test -e config.py || exit
test -e keystore.jks || exit

# if we can find the specific projects that want us, then narrow the APK
# search to just those subdirs
projects=`grep -F '<childProjects>update-debug-fdroid-repo</childProjects>' $apksource/jobs/*/config.xml \
    | sed -n 's,\(.*/config.xml\):.*,\1,p'`
if [ ! -z "$projects" ]; then
    apksource=$projects
fi

for f in `find $apksource -name '*.apk' 2> /dev/null \
    | grep '/bin/' | grep -F -v -e unaligned -e unsigned -e /archive/`; do
    name=$(basename $(dirname `dirname $f`))
    apk=`$aapt dump badging "$f" | sed -n "s,^package: name='\(.*\)' versionCode='\([0-9][0-9]*\)' .*,\1_\2.apk,p"`
    test $f -nt repo/$apk && rm -f repo/$apk  # delete existing if $f is newer
    if [ ! -e repo/$apk ] && [ ! -e archive/$apk ]; then
        echo "$f --> repo/$apk"
        ln $f repo/$apk || \
            ln -s $f repo/$apk || \
            rsync -axv $f repo/$apk # rsync if hard link is not possible
    fi
done

$fdroid update --verbose --delete-unknown
# post to repo on remote server
$fdroid server update --verbose
# post to local repo
rsync -axv --delete-after repo/ /var/www/fdroid/repo/
rsync -axv --delete-after archive/ /var/www/fdroid/archive/


# now manage per-app repos
basedir=`pwd`
echo "<html><body><ul>" > ~/debug/index.html
for d in ~/debug/[a-z.]*; do
    cd $basedir
    test -d $d || continue
    test -d $d/fdroid || continue
    test -d $d/fdroid/repo || continue
    packageName=`basename $d`
    icon=`cd ~/debug/ && ls -1 $packageName/fdroid/repo/icons-240/$packageName_*.png | sort -n | tail -1`
    echo "<li><a href=\"/debug/$packageName/fdroid/repo?fingerprint=F8ED4C73C125E7A67F99DB269480DAF50BE1758952E07EE5ABF116FE4B2DB1E8\"><img src=\"$icon\" /> $packageName</a></li>" >> ~/debug/index.html
    fdroiddir=~/debug/$packageName/fdroid
    for f in */$packageName*.apk; do
        test -r $f || continue
        if $aapt dump xmltree $f AndroidManifest.xml | grep 'android:debuggable.*0x0$'; then
            echo WARNING: ignoring release builds for now...
        else
            rsync -ax $f $fdroiddir/repo/
        fi
    done
    cd $d/fdroid
    $fdroid update --verbose --delete-unknown
    # post to repo on remote server
    $fdroid server update --verbose
    # post to local repo
    rsync -axv --delete-after $fdroiddir/repo/ /var/www/debug/$packageName/fdroid/repo/
    rsync -axv --delete-after $fdroiddir/archive/ /var/www/debug/$packageName/fdroid/archive/
done
echo "</ul></body></html>" >> ~/debug/index.html
cp ~/debug/index.html /var/www/debug/index.html
