#!/bin/bash

set -e
set -x

if [ $# -gt 0 ]; then
    apksource=$1
else
    apksource=~jenkins/
fi

if [ $# -gt 1 ]; then
    fdroid=$2
else
    fdroid="fdroid"
fi

if [ ! -d $apksource ]; then
    echo "APK source dir '$apksource' does not exist! Specify one:"
    echo "$0 /path/to/folder/with/apks [/path/to/fdroidserver/fdroid]"
    exit 1
fi

# allow the location of aapt to be overridden
if [ -z "$aapt" ]; then
    aapt=`ls -1 $ANDROID_HOME/build-tools/*/aapt | sort | tail -1`
fi

test -x $aapt || exit
test -d repo || exit
test -e config.py || exit
test -e keystore.jks || exit

# if we can find the specific projects that want us, then narrow the APK
# search to just those subdirs
projects=`grep -F '<childProjects>update-debug-fdroid-repo</childProjects>' $apksource/jobs/*/config.xml \
    | sed -n 's,\(.*/config.xml\):.*,\1,p'`
if [ ! -z "$projects" ]; then
    apksource=$projects
fi

for f in `find $apksource -name '*.apk' 2> /dev/null \
    | grep '/bin/' | grep -F -v -e unaligned -e unsigned -e /archive/`; do
    name=$(basename $(dirname `dirname $f`))
    apk=`$aapt dump badging "$f" | sed -n "s,^package: name='\(.*\)' versionCode='\([0-9][0-9]*\)' .*,\1_\2.apk,p"`
    test $f -nt repo/$apk && rm -f repo/$apk  # delete existing if $f is newer
    if [ ! -e repo/$apk ] && [ ! -e archive/$apk ]; then
        echo "$f --> repo/$apk"
        ln $f repo/$apk || \
            ln -s $f repo/$apk || \
            rsync -axv $f repo/$apk # rsync if hard link is not possible
    fi
done

$fdroid update --verbose --delete-unknown
# post to repo on remote server
$fdroid server update --verbose
# post to local repo
rsync -axv --delete-after repo/ /var/www/fdroid/repo/
rsync -axv --delete-after archive/ /var/www/fdroid/archive/

read -d '' htmlheader <<"EOF"
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Guardian Project Test Build Repository</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel='stylesheet' id='admin-bar-css'  href='/fdroid/admin-bar.min.css?ver=3.7.1' type='text/css' media='all' />
    <link rel='stylesheet' id='responsive-style-css'  href='/fdroid/style.css?ver=1.9.3.4' type='text/css' media='all' />
    <link rel='stylesheet' id='responsive-media-queries-css'  href='/fdroid/core-css-style.css?ver=1.9.3.4' type='text/css' media='all' />

    <style media="screen" type="text/css">
        img {vertical-align:middle}
        li {font-size: 200%; font-family:Inconsolata,monospace}
        ul {list-style-type: none}
    </style>
</head>

<body>
    <div id="logo">
        <a href="https://guardianproject.info/"><img src="/fdroid/cropped-GP_logo+txt_hires_black_on_trans_header.png" width="950" height="120" alt="The Guardian Project"/></a>
    </div>
    <!-- end of #logo -->

    <div id="container" class="hfeed">
        <div id="wrapper" class="clearfix">
          <div id="widgets" class="home-widgets">
            <div class="widget-title-home"><h2>Guardian Project Test Build Repository</h2></div>
            <div class="textwidget">
              This is our <a href="https://f-droid.org"
                target="_blank">FDroid</a> app repository for our builds of
                  our apps.  This repository and the apps it contains should
                  only be used for testing.  <strong>These are not secure, final
                  versions of our software!</strong>
              </div>

    <ul>
EOF
echo "$htmlheader" > ~/debug/index.html

# now manage per-app repos
basedir=`pwd`
for d in ~/debug/[a-z.]*; do
    cd $basedir
    test -d $d || continue
    test -d $d/fdroid || continue
    test -d $d/fdroid/repo || continue
    packageName=`basename $d`
    icon=`cd ~/debug/ && ls -1 $packageName/fdroid/repo/icons-240/$packageName_*.png | sort -n | tail -1`
    urlpath="/debug/$packageName/fdroid/repo?fingerprint=F8ED4C73C125E7A67F99DB269480DAF50BE1758952E07EE5ABF116FE4B2DB1E8"
    echo "<li><a href=\"$urlpath\"><img src=\"/debug/$icon\" /><h2>$packageName</h2></a></li>" >> ~/debug/index.html
    fdroiddir=~/debug/$packageName/fdroid
    qrpng=$fdroiddir/repo/qr.png
    repoindex=$fdroiddir/repo/index.html
    qr "https://dev.guardianproject.info$urlpath" > $qrpng
    echo '<html><body><h1>https://dev.guardianproject.info$urlpath</h1><img src="qr.png" /></body></html>' > $repoindex
    for f in */$packageName*.apk; do
        test -r $f || continue
        if $aapt dump xmltree $f AndroidManifest.xml | grep 'android:debuggable.*0x0$'; then
            echo "WARNING: ignoring release builds for now..."
        else
            rsync -ax $f $fdroiddir/repo/
        fi
    done
    cd $d/fdroid
    $fdroid update --verbose --delete-unknown
    # post to repo on remote server
    $fdroid server update --verbose
    # post to local repo
    rsync -axv --delete-after $fdroiddir/repo/ /var/www/debug/$packageName/fdroid/repo/
    rsync -axv --delete-after $fdroiddir/archive/ /var/www/debug/$packageName/fdroid/archive/
done

read -d '' htmlfooter <<"EOF"
    </ul>
    <br style="clear:both;"/>

    <h2>Signing Key Fingerprint</h2>
    <div class="textwidget">
      If you would like to manually verify the fingerprint (SHA-256)
      of the repository signing key, here it is:
      <pre>F8&nbsp;ED&nbsp;4C&nbsp;73&nbsp;C1&nbsp;25&nbsp;E7&nbsp;A6&nbsp;7F&nbsp;99&nbsp;DB&nbsp;26&nbsp;94&nbsp;80&nbsp;DA&nbsp;F5&nbsp;0B&nbsp;E1&nbsp;75&nbsp;89&nbsp;52&nbsp;E0&nbsp;7E&nbsp;E5&nbsp;AB&nbsp;F1&nbsp;16&nbsp;FE&nbsp;4B&nbsp;2D&nbsp;B1&nbsp;E8</pre>
    </div>
    
    <h2>Questions or Problems?</h2>
    <div class="textwidget">
      If you have any questions or problems please email us
          at:<address><a
          href="mailto:support@guardianproject.info">support@guardianproject.info</a></address>
          or <a href="https://guardianproject.info/contact/chat/"
          target="_blank">ask in our chat room</a>.
    </div>
    </div>
    </div>
</body></html>
EOF
echo "$htmlfooter" >> ~/debug/index.html


cp ~/debug/index.html /var/www/debug/index.html
